### ISSUE TITLE
Documentación Django

### ISSUE THREAD

**Issue by OIMA** [gmlp/linux_performance_analysis#1]
Chavos necesito que documenten en uno o más archivos con extensión.md y formato markdown todo lo que vayan haciendo, desde la instalación de Django hasta la arquitectura de desarrollo. Aprovechando que usan distintas distribuciones, complementenla tanto para Redhat cómo Debian.
Sugiero creen un directorio llamado Docs. Después se organizará en las Wikis del proyecto. 

Saludos.

**Comment by OIMA** [comment]
Bien por la doc @josejames, también utilicen este medio para comentar sobre el estado del proyecto. En cuanto pueda trataré de echar a andar lo que llevan, si hace falta algo abriré más issues. 

**Nota:** No encontré el archivo requirements.txt, procuren poner un enlace al archivo.

**Comment by josejames** [comment]
ya está en la carpeta Docs el archivo requirements.txt

**Comment by OIMA** [comment]
El enlace debe ser con sintaxis markdown, similar a la siguiente.[requirements.txt](https://github.com/gmlp/linux_performance_analysis/blob/django_master/web_scripts/Docs/requirements.txt)
